update chapter 1
KaiWu1101/yocto-project-translation-cn pull request #3
Opened 2020-03-23 18:16 UTC by KaiWu1101

update chapter 1 of The Yocto Project Overview and Concepts Manual

2020-03-26 12:25 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这篇手册是对yocto项目的总览，同时对一些常用术语和概念做了解释，提供了更深入的相关链接．一共分为四个小章节
"提供了更深入的相关链接"
=> “并提供相关链接以便于深入了解”

2020-03-27 21:26 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这篇手册是对yocto项目的总览，同时对一些常用术语和概念做了解释，提供了更深入的相关链接．一共分为四个小章节
已经修改

2020-03-28 20:58 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这篇手册是对yocto项目的总览，同时对一些常用术语和概念做了解释，提供了更深入的相关链接．一共分为四个小章节
如果审阅可以的话 帮我merge了吧

2020-04-01 13:14 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +欢迎来到yocto项目总览和术语手册，这个手册通过向新手提供概念讲解，软件概述，最合适有效的开发方法介绍以及其他总览性的信息说明的方法让新手了解yocto项目。
这个手册~~通过向新手~~提供概念讲解，软件概述，**最为熟知**的开发方法**~~介绍~~**以及其他总览性的信息~~说明的方法~~，让新手了解yocto项目。

2020-04-01 13:22 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +第二章介绍了yocto，你会在第二章学到yocto的特点和你在学习中会遇到的挑战,你也会接触一下这些概念: 分层模型，工具和部件，开发方法，poky参考发行版, OpenEmbedded构建系统的工作流程和一些yocto术语.
1. 你也会接触**以下**这些概念:
2. **组件和工具**

2020-04-01 13:25 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +第三章开始让你了解yocto的开发环境，你会学习到有关开源，开发主机（你用来写代码的机子）， yocto仓库，使用git的工作流程（原文是workflows using Git), 简单的git入门以及许可证的知识(licensing).
开发主机~~（你用来写代码的机子）~~
使用git的工作流程~~（原文是workflows using Git)~~

2020-04-01 13:28 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这个手册不会提供给你一下信息
**以下**

2020-04-01 13:29 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +不包含一步步具体的开发步骤，具体的有关步骤会在 Yocto Project Development Tasks Manual 这个手册中涉及，而Yocto Project Application Development and the Extensible Software Development Kit (eSDK) manual这个手册中包含了如何安装SDK来开发应用的具体步骤
文档缺少链接

2020-04-01 13:30 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +不包含一步步具体的开发步骤，具体的有关步骤会在 Yocto Project Development Tasks Manual 这个手册中涉及，而Yocto Project Application Development and the Extensible Software Development Kit (eSDK) manual这个手册中包含了如何安装SDK来开发应用的具体步骤
如何安装SDK**为目标硬件**来开发应用的具体步骤

2020-04-01 13:30 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +不包含具体的参考材料，系统变量等参考或者需要查找的信息这个手册中： Yocto Project Reference Manual. 而[Yocto Project Board Support Package (BSP) Developer's Guide](https://www.yoctoproject.org/docs/2.7/bsp-guide/bsp-guide.html)包含了BSP相
参考文档缺少链接

2020-04-01 13:35 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +不包含一些和yocto不怎么相关的公开信息（public information),　比如说如何使用git就不会在这个手册中提及．
不包含诸如如何使用Git这样不应由Yocto文档详细说明的信息，你应该去查阅官方文档或者通过搜索引擎查找资料。

2020-04-01 13:38 UTC, KimChan2013 requested changes
几个小地方的comment。
其他没有问题。

2020-04-01 21:02 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +欢迎来到yocto项目总览和术语手册，这个手册通过向新手提供概念讲解，软件概述，最合适有效的开发方法介绍以及其他总览性的信息说明的方法让新手了解yocto项目。
已经修改

2020-04-01 21:21 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +第三章开始让你了解yocto的开发环境，你会学习到有关开源，开发主机（你用来写代码的机子）， yocto仓库，使用git的工作流程（原文是workflows using Git), 简单的git入门以及许可证的知识(licensing).
已经修改

2020-04-01 21:21 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +第二章介绍了yocto，你会在第二章学到yocto的特点和你在学习中会遇到的挑战,你也会接触一下这些概念: 分层模型，工具和部件，开发方法，poky参考发行版, OpenEmbedded构建系统的工作流程和一些yocto术语.
已经修改

2020-04-01 21:21 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这个手册不会提供给你一下信息
已经修改

2020-04-01 21:21 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +不包含一步步具体的开发步骤，具体的有关步骤会在 Yocto Project Development Tasks Manual 这个手册中涉及，而Yocto Project Application Development and the Extensible Software Development Kit (eSDK) manual这个手册中包含了如何安装SDK来开发应用的具体步骤
已经修改

2020-04-01 21:21 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +不包含具体的参考材料，系统变量等参考或者需要查找的信息这个手册中： Yocto Project Reference Manual. 而[Yocto Project Board Support Package (BSP) Developer's Guide](https://www.yoctoproject.org/docs/2.7/bsp-guide/bsp-guide.html)包含了BSP相
已经添加

2020-04-01 21:21 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +不包含一些和yocto不怎么相关的公开信息（public information),　比如说如何使用git就不会在这个手册中提及．
已经修改

2020-04-02 14:20 UTC, KimChan2013 approved these changes

2020-04-02 14:20 UTC, KimChan2013 approved these changes
OK

2020-04-02 14:20 UTC, merged