Add chapter2 of yocto overview and concepts manual
KaiWu1101/yocto-project-translation-cn pull request #6
Opened 2020-04-13 23:16 UTC by KaiWu1101

2020-04-15 12:35 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +## 2.1 什么是yoct
Yocto

2020-04-15 12:37 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这个在这里不重复介绍了，在(吴雨儿：怎么开始学习yocto?)<https://zhuanlan.zhihu.com/p/67453665>一文中中我已经提及了．你也可以查看Drew Moseley的<文章>(https://www.embedded.com/why-the-yocto-project-for-my-iot-project/)或者观看这个视频(https://www.youtub
一文中~~中~~

2020-04-15 12:48 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**yocto在行业被普遍接受**，很多公司企业都使用了yocto作为生产工具，也有很庞大的社区支持
**行业广泛应用**：很多半导体，操作系统，软件和服务提供商的产品以及服务都采用并支持Yocto Project。你可以在[Yocto Project](http://www.yoctoproject.org/)网站的"COMMUNITY"和"EOSYSTEM"标签下查看Yocto Project社区和参与Yocto Project维护的公司信息。

2020-04-15 12:59 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**yocto支持很多架构** 比如ARM, MIPS, AMD, PPC等．很多芯片供应商也为他们的硬件制作和提供了BSPs，你也可以为自己的硬件制作BSP, yocto还通过QEMU支持硬件设备的仿真
大多数ODM，OSV（译者注：暂未查明ODM，OSV含义）和芯片提供商会制作并提供硬件的BSP包，你也可以为自己的硬件制作BSP包。
此外，Yocto Project还通过QEMU支持硬件设备的仿真。

2020-04-15 13:05 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**Yocto的输出（映像，编译好的应用）可以很容易的迁移到新的架构上** 如果你使 yocto制作了自己的映像(image)和应用，但是你不能长期支持的话，一些商业的linux供应商（比如说 wind river, mentor graphic, timesys and ENEA)可以帮助你维护它。(这一段说实话没看太懂，应该是说这些厂商能帮你维护你的yocto开发成果，如果yocto升级的话
**镜像及代码地移植非常容易**：Yocto Project的输出可以在不移动到新的开发环境情况下，很容易地就能迁移到新的架构上。如果你使用Yocto Project创建了镜像或者是应用，但同时你发现你无法为此提供支持，诸如Wind River，Mentor Graphics，Timesys，和ENEA这样的商业Linux提供商可以接手并提供后续支持。

2020-04-15 13:06 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**灵活性** 企业有很多种方法来使用yocto, 比如说可以制作比个linux映像作为基础(base), 然后把这个映像给多个不同的部门，让他们在此基础上根据部门产品开发自己的应用，作为各自的产品。通俗一点说就是给几个人一个一样的毛坯房，但是房子里装什么由他们自己决定。
比个->一个

2020-04-15 13:07 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**适合资源受限的嵌入式或者IOT设备** 不同于完整的发行版(比如说ubuntu), yocto能让你自定义你的映像，你可以决定放哪些功能或者模块到你的映像中，比如说很多设备没有显示屏幕，那么像X11, GTK+, Qt或者SDL之类的组件就能不安装。最终的映像会足够小，而且没有多余的功能。
就**不需要**安装

2020-04-15 13:12 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**全面的toolchain支持** yocto已有的toolchain对大部分生产环境已经适用了， 如果你想自定义自己的toolchain,在yocto中也能通过更改平台参数来自定义你的toolchain,你也可以使用第三方toolchain.
tool chain可以直接翻译成工具链

2020-04-15 13:17 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这个没看懂， 原文如下: Mechanism Rules Over Policy:Focusing on mechanism rather than policy ensures that you are free to set policies based on the needs of your design instead of adopting decisions enforced by
同不理解....   这一小节之前也尝试翻译过，这段我也直接保留的原文

2020-04-15 13:19 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**使用了分层的模型(layer model)** 把相关的功能捆绑在一层，减少了项目的复杂性和冗余性，也易于维护和调试，这里的层更多的是并列关系，很少有上下层的关系，不好翻译这个layer, 因为我们看到 层 的时候就会默认有级别关系，上下或者包含的关系。。
**使用分层模型**：Yocto Project分层架构将相关联功能组合到不同的bundle中，你可以根据项目需求增加层(Layer)，这样做的好处是降低项目复杂性和重复性，方便系统扩展，定制化，保持功能有组织地管理

2020-04-15 13:20 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +支持局部构建（partial builds),你能单独构建某个包（package)或者层(layer)。 yocto 使用shared-state cache方法来实现这一点，（在build目录下有个sstate-control的目录）
格式：   **支持局部构建**

2020-04-15 13:21 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +支持局部构建（partial builds),你能单独构建某个包（package)或者层(layer)。 yocto 使用shared-state cache方法来实现这一点，（在build目录下有个sstate-control的目录）
sstate缺少链接

2020-04-15 13:22 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**严格的发布计划** 大版本发布每六个月一次，分别是每年的六月和十月。
十月和四月

2020-04-15 13:24 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**许可证清单** yocto能提供所有构建所需包的许可证清单，能让你追踪你项目中用到的开源许可证。 简单来说就是让你知道， 你都使用了哪些包，都是哪来的，会不会让你惹上官司)
许可证清单  <- 缺少链接

2020-04-15 13:26 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**陡峭的学习曲线** 这点不多说，不然我也就不在这里写文章翻译了。
Yocto Project拥有陡峭的学习曲线，相似的任务可以有诸多方式完成。有的时候，既定任务会有很多方式去完成，这可能会让你有选择困难症。

2020-04-15 13:28 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**项目的工作流程可能很让你困惑** 因为一般在发行版上安装程序包很容易(使用apt-get等），使用工具直接安装远端已经编译好的包。而在yocto中你必须改动你的配置并且重新构建来添加应用或者包。
这一段最好完整翻译下，原文中有其他章节的refer link

2020-04-15 13:33 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**交叉构建环境的不熟悉** 简单来说就是你的开发环境和你的部署环境不一致。所以需要交叉编译。
同上，需要完整翻译

2020-04-15 13:35 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> - 熟悉<Yocto Project curated layer index>(https://caffelli-staging.yoctoproject.org/software-overview/layers/) 和<OpenEmbedded layer index>(http://layers.openembedded.org/layerindex/branch/master/laye
后者包含更多Layer，但并不是都经过了验证

2020-04-15 13:38 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> - <Yocto Project Compatible>(http://www.yoctoproject.org/docs/2.7/dev-manual/dev-manual.html#making-sure-your-layer-is-compatible-with-yocto-project) 简单来说就是让你的layer通过一个脚本测试，然后填写一个表格,之后yocto授权你使用Yoc
最后的译者注释可以删去，参考的是开发手册，到时候开发手册翻译好了就有参考了。

2020-04-15 13:46 UTC, KimChan2013 requested changes
部分段落需要完整翻译

2020-04-16 08:29 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +## 2.1 什么是yoct
标题没有显示在目录中

2020-04-16 08:29 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- [2.2 yocto的分层模型（layer model)](2.2-yocto的分层模)
目录格式（层级）不对

2020-04-16 08:30 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**yocto在行业被普遍接受**，很多公司企业都使用了yocto作为生产工具，也有很庞大的社区支持
这里格式也不对。应该是个列表：

- 1
- 2
- 3

2020-04-16 08:31 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**灵活性** 企业有很多种方法来使用yocto, 比如说可以制作比个linux映像作为基础(base), 然后把这个映像给多个不同的部门，让他们在此基础上根据部门产品开发自己的应用，作为各自的产品。通俗一点说就是给几个人一个一样的毛坯房，但是房子里装什么由他们自己决定。
标题 灵活性 后应该跟一个冒号。其他列表同理

2020-04-19 12:46 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +## 2.1 什么是yoct
已经修改

2020-04-19 12:46 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这个在这里不重复介绍了，在(吴雨儿：怎么开始学习yocto?)<https://zhuanlan.zhihu.com/p/67453665>一文中中我已经提及了．你也可以查看Drew Moseley的<文章>(https://www.embedded.com/why-the-yocto-project-for-my-iot-project/)或者观看这个视频(https://www.youtub
已经修改

2020-04-19 12:57 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**yocto在行业被普遍接受**，很多公司企业都使用了yocto作为生产工具，也有很庞大的社区支持
已经修改

2020-04-19 13:07 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**yocto支持很多架构** 比如ARM, MIPS, AMD, PPC等．很多芯片供应商也为他们的硬件制作和提供了BSPs，你也可以为自己的硬件制作BSP, yocto还通过QEMU支持硬件设备的仿真
Original design manufacturer
Operation System Vendors

2020-04-19 13:07 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**yocto支持很多架构** 比如ARM, MIPS, AMD, PPC等．很多芯片供应商也为他们的硬件制作和提供了BSPs，你也可以为自己的硬件制作BSP, yocto还通过QEMU支持硬件设备的仿真
已经修改

2020-04-19 13:12 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**Yocto的输出（映像，编译好的应用）可以很容易的迁移到新的架构上** 如果你使 yocto制作了自己的映像(image)和应用，但是你不能长期支持的话，一些商业的linux供应商（比如说 wind river, mentor graphic, timesys and ENEA)可以帮助你维护它。(这一段说实话没看太懂，应该是说这些厂商能帮你维护你的yocto开发成果，如果yocto升级的话
已经修改

2020-04-19 13:12 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**灵活性** 企业有很多种方法来使用yocto, 比如说可以制作比个linux映像作为基础(base), 然后把这个映像给多个不同的部门，让他们在此基础上根据部门产品开发自己的应用，作为各自的产品。通俗一点说就是给几个人一个一样的毛坯房，但是房子里装什么由他们自己决定。
已经修改

2020-04-19 13:13 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**适合资源受限的嵌入式或者IOT设备** 不同于完整的发行版(比如说ubuntu), yocto能让你自定义你的映像，你可以决定放哪些功能或者模块到你的映像中，比如说很多设备没有显示屏幕，那么像X11, GTK+, Qt或者SDL之类的组件就能不安装。最终的映像会足够小，而且没有多余的功能。
已经修改

2020-04-19 13:13 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**全面的toolchain支持** yocto已有的toolchain对大部分生产环境已经适用了， 如果你想自定义自己的toolchain,在yocto中也能通过更改平台参数来自定义你的toolchain,你也可以使用第三方toolchain.
已经修改

2020-04-19 13:18 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**使用了分层的模型(layer model)** 把相关的功能捆绑在一层，减少了项目的复杂性和冗余性，也易于维护和调试，这里的层更多的是并列关系，很少有上下层的关系，不好翻译这个layer, 因为我们看到 层 的时候就会默认有级别关系，上下或者包含的关系。。
已经修改

2020-04-19 13:19 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +支持局部构建（partial builds),你能单独构建某个包（package)或者层(layer)。 yocto 使用shared-state cache方法来实现这一点，（在build目录下有个sstate-control的目录）
已经修改

2020-04-19 13:19 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**严格的发布计划** 大版本发布每六个月一次，分别是每年的六月和十月。
已经修改

2020-04-19 13:20 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**许可证清单** yocto能提供所有构建所需包的许可证清单，能让你追踪你项目中用到的开源许可证。 简单来说就是让你知道， 你都使用了哪些包，都是哪来的，会不会让你惹上官司)
已经修改

2020-04-19 13:21 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**陡峭的学习曲线** 这点不多说，不然我也就不在这里写文章翻译了。
已经修改

2020-04-19 13:40 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**项目的工作流程可能很让你困惑** 因为一般在发行版上安装程序包很容易(使用apt-get等），使用工具直接安装远端已经编译好的包。而在yocto中你必须改动你的配置并且重新构建来添加应用或者包。
已经完整翻译

2020-04-19 13:41 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**交叉构建环境的不熟悉** 简单来说就是你的开发环境和你的部署环境不一致。所以需要交叉编译。
已经完整翻译

2020-04-19 13:42 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> - 熟悉<Yocto Project curated layer index>(https://caffelli-staging.yoctoproject.org/software-overview/layers/) 和<OpenEmbedded layer index>(http://layers.openembedded.org/layerindex/branch/master/laye
已经修改

2020-04-19 13:43 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> - <Yocto Project Compatible>(http://www.yoctoproject.org/docs/2.7/dev-manual/dev-manual.html#making-sure-your-layer-is-compatible-with-yocto-project) 简单来说就是让你的layer通过一个脚本测试，然后填写一个表格,之后yocto授权你使用Yoc
已经删除

2020-04-19 13:43 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +## 2.1 什么是yoct
已经修改

2020-04-19 13:44 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- [2.2 yocto的分层模型（layer model)](2.2-yocto的分层模)
已经修改

2020-04-19 13:47 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这个没看懂， 原文如下: Mechanism Rules Over Policy:Focusing on mechanism rather than policy ensures that you are free to set policies based on the needs of your design instead of adopting decisions enforced by
:satisfied:

2020-04-19 14:01 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这个在这里不重复介绍了，在(吴雨儿：怎么开始学习yocto?)<https://zhuanlan.zhihu.com/p/67453665>一文中中我已经提及了．你也可以查看Drew Moseley的<文章>(https://www.embedded.com/why-the-yocto-project-for-my-iot-project/)或者观看这个视频(https://www.youtub
这段文字中的两个链接不对，应该用"[]()"这个格式

2020-04-19 14:05 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**Yocto的输出（映像，编译好的应用）可以很容易的迁移到新的架构上** 如果你使 yocto制作了自己的映像(image)和应用，但是你不能长期支持的话，一些商业的linux供应商（比如说 wind river, mentor graphic, timesys and ENEA)可以帮助你维护它。(这一段说实话没看太懂，应该是说这些厂商能帮你维护你的yocto开发成果，如果yocto升级的话
如果这段没有歧义的话英文部分可以删去了？

2020-04-19 14:07 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这个没看懂， 原文如下: Mechanism Rules Over Policy:Focusing on mechanism rather than policy ensures that you are free to set policies based on the needs of your design instead of adopting decisions enforced by
不过这里有一点点格式问题，这段也是列表显示，少了"-"

2020-04-19 14:13 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> - <Yocto Project Compatible>(http://www.yoctoproject.org/docs/2.7/dev-manual/dev-manual.html#making-sure-your-layer-is-compatible-with-yocto-project) 简单来说就是让你的layer通过一个脚本测试，然后填写一个表格,之后yocto授权你使用Yoc
链接格式不对

2020-04-19 14:13 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> - 熟悉<Yocto Project curated layer index>(https://caffelli-staging.yoctoproject.org/software-overview/layers/) 和<OpenEmbedded layer index>(http://layers.openembedded.org/layerindex/branch/master/laye
链接格式不对

2020-04-19 14:17 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**全面的toolchain支持** yocto已有的toolchain对大部分生产环境已经适用了， 如果你想自定义自己的toolchain,在yocto中也能通过更改平台参数来自定义你的toolchain,你也可以使用第三方toolchain.
只改了一个toolchain，还有四个

2020-04-19 14:22 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**当你项目出了问题你想弄清楚怎么修改，可能要花费你很多时间和努力** 这里先建议阅读<yocto避坑指南>(https://www.yoctoproject.org/docs/what-i-wish-id-known/) 和 <开始使用yocto项目前的准备工作>(http://www.yoctoproject.org/docs/transitioning-to-a-custom-enviro
链接格式不对

2020-04-19 14:22 UTC, KimChan2013 requested changes
还有一些格式需要改下

2020-04-20 00:34 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这个在这里不重复介绍了，在(吴雨儿：怎么开始学习yocto?)<https://zhuanlan.zhihu.com/p/67453665>一文中中我已经提及了．你也可以查看Drew Moseley的<文章>(https://www.embedded.com/why-the-yocto-project-for-my-iot-project/)或者观看这个视频(https://www.youtub
已经修改

2020-04-20 00:34 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**Yocto的输出（映像，编译好的应用）可以很容易的迁移到新的架构上** 如果你使 yocto制作了自己的映像(image)和应用，但是你不能长期支持的话，一些商业的linux供应商（比如说 wind river, mentor graphic, timesys and ENEA)可以帮助你维护它。(这一段说实话没看太懂，应该是说这些厂商能帮你维护你的yocto开发成果，如果yocto升级的话
已经删除

2020-04-20 00:36 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**全面的toolchain支持** yocto已有的toolchain对大部分生产环境已经适用了， 如果你想自定义自己的toolchain,在yocto中也能通过更改平台参数来自定义你的toolchain,你也可以使用第三方toolchain.
都改成了中文翻译

2020-04-20 00:37 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +这个没看懂， 原文如下: Mechanism Rules Over Policy:Focusing on mechanism rather than policy ensures that you are free to set policies based on the needs of your design instead of adopting decisions enforced by
已经修改

2020-04-20 00:40 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> - 熟悉<Yocto Project curated layer index>(https://caffelli-staging.yoctoproject.org/software-overview/layers/) 和<OpenEmbedded layer index>(http://layers.openembedded.org/layerindex/branch/master/laye
已经修改，在前面又找到两个链接格式错误，也改了

2020-04-20 00:42 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> - <Yocto Project Compatible>(http://www.yoctoproject.org/docs/2.7/dev-manual/dev-manual.html#making-sure-your-layer-is-compatible-with-yocto-project) 简单来说就是让你的layer通过一个脚本测试，然后填写一个表格,之后yocto授权你使用Yoc
已经修改

2020-04-20 00:42 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +**当你项目出了问题你想弄清楚怎么修改，可能要花费你很多时间和努力** 这里先建议阅读<yocto避坑指南>(https://www.yoctoproject.org/docs/what-i-wish-id-known/) 和 <开始使用yocto项目前的准备工作>(http://www.yoctoproject.org/docs/transitioning-to-a-custom-enviro
已经修改

2020-04-20 03:00 UTC, KimChan2013 approved these changes

2020-04-20 03:01 UTC, merged