Section 2 2 of yocto overview and concepts manual
KaiWu1101/yocto-project-translation-cn pull request #8
Opened 2020-05-15 15:37 UTC by KaiWu1101

2020-05-25 13:46 UTC, KimChan2013 requested changes
主要是格式，有一段没翻译的我试着翻译了，个别词语有点拗口，你也可以再看下

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +### 2.3.1
### 2.3.1 开发工具

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- [CROPS](https://git.yoctoproject.org/cgit/cgit.cgi/crops/about/)：使用了[Docker技术](https://www.docker.com/)的开源的跨平台yocto开发工具，简单来说就是如果你是windows，但是你要使用yocto开发的话，这东西用得着。本来就是使用linux的开发者应该不需要它。
使用了[Docker容器](https://www.docker.com/)技术的开源跨平台开发框架。CROPS提供一套易于管理且扩展性强的环境，帮助你在Windows，Linux和Mac OS X系统上构建目标代码。

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- devtool: 这个命令行工具是eSDK中很重要的一部分（原文是conerstone part),你可以使用devtool来帮助构建，测试和打包软件。你也能用它来选择你想集成到映像(image)中的软件和功能。devtool有一系列的子命令来让你添加，修改或者升级你的recipes. 当你用**devtool add**添加软件或者功能的时候，它会自动帮你生成一个recipe. 当你使用*
缺少段落格式，这里应该是两段

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- devtool: 这个命令行工具是eSDK中很重要的一部分（原文是conerstone part),你可以使用devtool来帮助构建，测试和打包软件。你也能用它来选择你想集成到映像(image)中的软件和功能。devtool有一系列的子命令来让你添加，修改或者升级你的recipes. 当你用**devtool add**添加软件或者功能的时候，它会自动帮你生成一个recipe. 当你使用*
_devtool:_ 这个命令行工具是eSDK中很重要的一部分,你可以使用`devtool`来帮助构建，测试和打包软件。你也能用它来选择你想集成到镜像中的软件和功能。

`devtool`有一系列的子命令来让你添加，修改或者升级你的recipes. 和OE构建系统一样，`devtool`中recipes即软件包的概念。当使用`devtool add`命令时，它会自动帮你生成一个recipe. 当你使用`devtool modify`的时候，可以为一个已有的recipe来决定从哪里获取源代码，以及如何为之打补丁。这两种情况下，`devtool`都会为你设置一个环境，以确保在构建配方时使用的是在你控制下的源码树，以便于你可以根据需要对源码进行修改。

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +默认情况下，新的配方文件和新的源代码都会存储在eSDK下的工作区。 **devtool upgrade**命令会更新旧的配方文件，这样你就能根据新的源代码和配方构建一个软件包。
默认情况下，新的配方文件和新的源代码都会存储在eSDK下的工作区。 `devtool upgrade`命令会更新旧的配方文件，这样你就能根据新的源代码构建一个软件包。

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- [CROPS](https://git.yoctoproject.org/cgit/cgit.cgi/crops/about/)：使用了[Docker技术](https://www.docker.com/)的开源的跨平台yocto开发工具，简单来说就是如果你是windows，但是你要使用yocto开发的话，这东西用得着。本来就是使用linux的开发者应该不需要它。
**[CROPS](https://git.yoctoproject.org/cgit/cgit.cgi/crops/about/)**

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +关于devtool 详情请阅读Yocto项目应用开发和可扩展软件开发工具包手册的[在SDK工作流程中使用devtool](http://www.yoctoproject.org/docs/2.7/sdk-manual/sdk-manual.html#using-devtool-in-your-sdk-workflow)这一章节
devtool -> `devtool`

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- 可扩展软件开发工具包(eSDK): eSDK提供了交叉开发的工具链和为具体镜像而裁剪的库。eSDK使得添加新的应用和库文件，修改源代码，在目标板上测试修改以及把其他部件集成到OE构建系统中这些操作变得更加容易。 eSDK为你提供了工具链，并且Yocto项目环境量身定制了功能强大的devtool指令集
可扩展软件开发工具包(eSDK) -> **可扩展软件开发工具包(eSDK)**

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- 可扩展软件开发工具包(eSDK): eSDK提供了交叉开发的工具链和为具体镜像而裁剪的库。eSDK使得添加新的应用和库文件，修改源代码，在目标板上测试修改以及把其他部件集成到OE构建系统中这些操作变得更加容易。 eSDK为你提供了工具链，并且Yocto项目环境量身定制了功能强大的devtool指令集
eSDK借由为Yocto Project环境裁剪的一套功能强大的`devtool`命令，可以为你提供更好的工具链体验。

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +[关于eSDK的更多信息可以参考Yocto项目应用开发和可扩展软件开发工具包手册](http://www.yoctoproject.org/docs/2.7/sdk-manual/sdk-manual.html)
关于eSDK的更多信息可以参考[Yocto项目应用开发和可扩展软件开发工具包手册](http://www.yoctoproject.org/docs/2.7/sdk-manual/sdk-manual.html)

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +Toaster: yocto项目构建系统的网页界面版本, 能让你配置，运行和查看构建信息。查看[Toaster用户手册](http://www.yoctoproject.org/docs/2.7/toaster-manual/toaster-manual.html)可以得到更多Toaster信息
Toaster -》 **Toaster**

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +### 2.3.2
### 2.3.2 生产工具

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Auto Upgrade Helper: 如果上游对应配方文件更新的话，这个工具配合[OE构建系统](http://www.yoctoproject.org/docs/2.7/ref-manual/ref-manual.html#build-system-term)(Bitbake和OE-Core)自动升级更新配方文件这个工具和bitbake一起能自动帮你升级从远端获取的recipes，我的
**Auto Upgrade Helper**: 如果上游对应配方文件更新的话，这个工具配合[OE构建系统](http://www.yoctoproject.org/docs/2.7/ref-manual/ref-manual.html#build-system-term)(Bitbake和OE-Core)自动升级更新配方文件这个工具和bitbake一起能自动帮你升级从远端获取的recipes。

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Recipe Reporting System: 这个系统跟踪Yocto Project可用的配方版本，帮助你管理你的项目同时提供给你一个关于你项目的概述，简单的说是告诉你的使用的recipes是哪来的，哪些在继续更新，哪些版本能用。这个系统是基于[OE的层索引目录 OpenEmbedded Layer Index](http://layers.openembedded.org/layeri
**Recipe Reporting System**: 这个系统跟踪Yocto Project可用的配方版本，帮助你管理项目同时提供给你一个动态项目概述。这个系统基于[OE的层索引目录 OpenEmbedded Layer Index](http://layers.openembedded.org/layerindex/layers/)构建 。

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Patchwork: 开发者用来管理补丁的，让开发者更有效率的为yocto项目做更改。[Patchwork](http://jk.ozlabs.org/projects/patchwork/)这个项目由OzLabs发起](http://ozlabs.org/)
**Patchwork**:[Patchwork](http://jk.ozlabs.org/projects/patchwork/)这个项目由[OzLabs](http://ozlabs.org/)发起。Yocto Project使用Patchwork作为管理工具来管理补丁，让开发者更有效率地为项目做更改。

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- AutoBuilder:这里翻译为自动构建者，用来做自动测试和QA(quality assurance)的。能定期的构建，运行测试用例，帮助开发者发现新引入的bug。Yocto社区也鼓励开发者提交测试计划和自动测试工具。
**AutoBuilder**: Autobuilder用来做自动测试和QA(quality assurance)，每个人都可以利用公共的AutoBuilder查看Pock master分支的状态。

Kim注： Autobuilder是工具名称，不用翻译

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> 这个工具基于[buildbot](https://buildbot.net/)。
Autobuilder基于[buildbot](https://buildbot.net/)

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +
Yocto Project的目标之一是创建一个能够进行自动测试和QA质量保证的开源项目。为了达到这个目标，Yocto Project鼓励开发社区发布QA、测试计划，并提供公开演讲，鼓励为开发社区提交自动化测试工具以及QA流程。

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Cross-Prelink:没看太懂，估计也不会用到。好像是预链接的工具，通过库共享能减少构建的软件运行时需要的内存
**Cross-Prelink**:  相比较于运行时进行操作，预链接(preliking)是一个预先计算由动态链接器生成的加载地址和链接表的过程。这样做的好处是，提升应用程序启动性能，减少应用共用lib库的内存使用量。
cross-prelink是由[Jakub Jelínek](http://people.redhat.com/jakub/prelink.pdf)设计的prelink的一个变体，prelink和cross-prelink在同一个仓库不同的两个分支。通过提供一个模拟运行时动态连接器(即glibc衍生的ld.so仿真)cross-prelink project扩展了prelink软件的能力，可以对sysroot环境进行预先链接。不仅如此，cross-prelink软件也拥有在类sysroot环境中工作的能力。
动态链接器根据一系列因素，例如映射地址，lib库使用情况，lib函数冲突等，进行标准的加载地址计算。prelink工具利用动态链接器的输入信息，决定共享库文件并动态链接的可执行可链接格式（ELF）的二进制文件的唯一加载地址。prelink工具根据预先计算的信息修改ELF二进制文件，这样做的好处是，重用利用COW技术（译者注：[COW写时复制](https://blog.csdn.net/u010712083/article/details/8963202)）的lib库文件，提升加载能力，降低内存消耗。
由于以来目标设备的动态链接器，prelink project仅仅支持在目标设备运行prelink，这导致开发跨平台系统时会产生诸多问题。cross-prelink添加了一个运行在（开发）主机上的综合动态加载器，允许不在目标系统上进行cross-prelinking。

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Cross-Prelink:没看太懂，估计也不会用到。好像是预链接的工具，通过库共享能减少构建的软件运行时需要的内存
格式你可能还得修改下，主要是换行

2020-05-25 13:46 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Pseudo: 在构建的过程中可能会需要系统权限，这个工具能让你在构建的过程中作为非root用户暂时获得root权限，你能直接用这个工具，也能通过变量LD_PRELOAD来设置。后面会有解释。
**Pseudo**: 在构建的过程中可能会需要系统权限，这个工具能让你在构建的过程中作为非root用户暂时获得root权限，你能直接用这个工具，也能通过变量LD_PRELOAD来设置。详细介绍可参考[fakeroot](http://man.he.net/man1/fakeroot).

2020-05-25 17:09 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +### 2.3.1
已修改

2020-05-25 17:09 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- [CROPS](https://git.yoctoproject.org/cgit/cgit.cgi/crops/about/)：使用了[Docker技术](https://www.docker.com/)的开源的跨平台yocto开发工具，简单来说就是如果你是windows，但是你要使用yocto开发的话，这东西用得着。本来就是使用linux的开发者应该不需要它。
已修改

2020-05-25 17:15 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- devtool: 这个命令行工具是eSDK中很重要的一部分（原文是conerstone part),你可以使用devtool来帮助构建，测试和打包软件。你也能用它来选择你想集成到映像(image)中的软件和功能。devtool有一系列的子命令来让你添加，修改或者升级你的recipes. 当你用**devtool add**添加软件或者功能的时候，它会自动帮你生成一个recipe. 当你使用*
已修改

2020-05-25 17:16 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +默认情况下，新的配方文件和新的源代码都会存储在eSDK下的工作区。 **devtool upgrade**命令会更新旧的配方文件，这样你就能根据新的源代码和配方构建一个软件包。
已修改，把**改成了_

2020-05-25 17:19 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- [CROPS](https://git.yoctoproject.org/cgit/cgit.cgi/crops/about/)：使用了[Docker技术](https://www.docker.com/)的开源的跨平台yocto开发工具，简单来说就是如果你是windows，但是你要使用yocto开发的话，这东西用得着。本来就是使用linux的开发者应该不需要它。
这里2.3.1的标题已经改成了开发工具，这里可能和上面冲突了

2020-05-25 17:19 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +关于devtool 详情请阅读Yocto项目应用开发和可扩展软件开发工具包手册的[在SDK工作流程中使用devtool](http://www.yoctoproject.org/docs/2.7/sdk-manual/sdk-manual.html#using-devtool-in-your-sdk-workflow)这一章节
已修改

2020-05-25 17:31 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- 可扩展软件开发工具包(eSDK): eSDK提供了交叉开发的工具链和为具体镜像而裁剪的库。eSDK使得添加新的应用和库文件，修改源代码，在目标板上测试修改以及把其他部件集成到OE构建系统中这些操作变得更加容易。 eSDK为你提供了工具链，并且Yocto项目环境量身定制了功能强大的devtool指令集
修改为了:    
**借由为Yocto Project环境裁剪的一套功能强大的devtool指令集，eSDK可以为你提供更好的工具链体验**

2020-05-25 17:32 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +[关于eSDK的更多信息可以参考Yocto项目应用开发和可扩展软件开发工具包手册](http://www.yoctoproject.org/docs/2.7/sdk-manual/sdk-manual.html)
已修改

2020-05-25 17:32 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +Toaster: yocto项目构建系统的网页界面版本, 能让你配置，运行和查看构建信息。查看[Toaster用户手册](http://www.yoctoproject.org/docs/2.7/toaster-manual/toaster-manual.html)可以得到更多Toaster信息
已修改

2020-05-25 17:33 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +### 2.3.2
已修改

2020-05-25 17:34 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Auto Upgrade Helper: 如果上游对应配方文件更新的话，这个工具配合[OE构建系统](http://www.yoctoproject.org/docs/2.7/ref-manual/ref-manual.html#build-system-term)(Bitbake和OE-Core)自动升级更新配方文件这个工具和bitbake一起能自动帮你升级从远端获取的recipes，我的
已经修改

2020-05-25 17:36 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Recipe Reporting System: 这个系统跟踪Yocto Project可用的配方版本，帮助你管理你的项目同时提供给你一个关于你项目的概述，简单的说是告诉你的使用的recipes是哪来的，哪些在继续更新，哪些版本能用。这个系统是基于[OE的层索引目录 OpenEmbedded Layer Index](http://layers.openembedded.org/layeri
已经修改

2020-05-25 17:37 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Patchwork: 开发者用来管理补丁的，让开发者更有效率的为yocto项目做更改。[Patchwork](http://jk.ozlabs.org/projects/patchwork/)这个项目由OzLabs发起](http://ozlabs.org/)
已经修改

2020-05-25 17:43 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- AutoBuilder:这里翻译为自动构建者，用来做自动测试和QA(quality assurance)的。能定期的构建，运行测试用例，帮助开发者发现新引入的bug。Yocto社区也鼓励开发者提交测试计划和自动测试工具。
好的，Autobuiler不翻译了
修改为了    
**每个人都可以利用公共的AutoBuilder查看Poky的master分支状态**

2020-05-25 17:47 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +
按照修改了，其中一小段话另外改成了
**Yocto Project鼓励开发社区发布QA和测试计划，并公开演示QA和测试计划**

2020-05-25 18:25 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Cross-Prelink:没看太懂，估计也不会用到。好像是预链接的工具，通过库共享能减少构建的软件运行时需要的内存
谢谢翻译    
格式已经修改
- 减少应用共用lib库的内存使用量 ->>  减少应用程序之间共享库文件的内存使用量 
- cross-prelink软件也拥有在类sysroot环境中工作的能力。->>经过cross-prelink的软件也拥有在类sysroot环境中工作的能力
- prelink工具利用动态链接器的输入信息，决定那些可被动态链接和执行的ELF二进制文件的唯--  决定共享库文件并动态链接的可执行可链接格式（ELF）的二进制文件的唯一加载地址 --->>  决定那些可被动态链接和执行的ELF二进制文件的唯一加载地址(这些二进制文件就是指那些共享的库文件，就是决定*.so一类动态库文件的加载地址)      
- 这样做的好处是，重用利用COW技术（译者注：xxxxxxxx）的lib库文件 -->>这样做的好处是，重复利用COW(译者注xxxxxxxxx)内存页的共享lib库文件

2020-05-25 18:26 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- Pseudo: 在构建的过程中可能会需要系统权限，这个工具能让你在构建的过程中作为非root用户暂时获得root权限，你能直接用这个工具，也能通过变量LD_PRELOAD来设置。后面会有解释。
已经修改

2020-05-26 12:27 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- devtool: 这个命令行工具是eSDK中很重要的一部分（原文是conerstone part),你可以使用devtool来帮助构建，测试和打包软件。你也能用它来选择你想集成到映像(image)中的软件和功能。devtool有一系列的子命令来让你添加，修改或者升级你的recipes. 当你用**devtool add**添加软件或者功能的时候，它会自动帮你生成一个recipe. 当你使用*
devtool小标题粗体

2020-05-26 12:29 UTC, KimChan2013 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> 这个工具基于[buildbot](https://buildbot.net/)。
缩进还要改一下，开头要空格x2，

2020-05-26 12:31 UTC, KimChan2013 requested changes
只剩一个格式问题了，你改了就直接merge就行

2020-05-26 12:56 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +- devtool: 这个命令行工具是eSDK中很重要的一部分（原文是conerstone part),你可以使用devtool来帮助构建，测试和打包软件。你也能用它来选择你想集成到映像(image)中的软件和功能。devtool有一系列的子命令来让你添加，修改或者升级你的recipes. 当你用**devtool add**添加软件或者功能的时候，它会自动帮你生成一个recipe. 当你使用*
修改了

2020-05-26 13:01 UTC, KaiWu1101 commented on yocto项目总览和术语手册/yocto_project_overview_and_concepts_manual_cn.md
> +> 这个工具基于[buildbot](https://buildbot.net/)。
修改了

2020-05-26 13:02 UTC, merged